apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: mlflow-app:latest
          command: ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]
          ports:
            - containerPort: 5000
