name: CI/CD Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up QEMU (for multi-arch builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 5. Set lowercase username for image tags
      - name: Set lowercase username
        id: lowername
        run: echo "username_lc=${GITHUB_ACTOR,,}" >> $GITHUB_OUTPUT

      # 6. Build and push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest

      # 7. Set up Kind (Kubernetes in Docker)
      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.20.0

      # 8. Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      # 9. Create GHCR image pull secret inside Kind
      - name: Create GHCR image pull secret
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GHCR_PAT }} || echo "Secret already exists"

      # 10. Patch MLflow deployment to use imagePullSecret
      - name: Patch MLflow deployment for secret
        run: |
          kubectl patch deployment mlflow \
            --patch '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"ghcr-secret"}]}}}}' || echo "Deployment not created yet"

      # 11. Apply Kubernetes manifests
      - name: Apply K8s manifests
        run: |
          kubectl apply -f k8s/mlflow-pv-pvc.yaml
          kubectl apply -f k8s/mlflow-deployment.yaml
          kubectl apply -f k8s/mlflow-service.yaml

      # 12. Wait for MLflow server to be ready
      - name: Wait for MLflow readiness
        run: kubectl rollout status deployment/mlflow --timeout=300s

      # 13. Apply Trainer Job
      - name: Apply Trainer Job
        run: kubectl apply -f k8s/trainer-job.yaml

      # 14. Debug - List pods
      - name: Debug - List pods
        run: kubectl get pods -o wide

      # 15. Debug - Describe trainer job
      - name: Debug - Describe trainer job
        run: kubectl describe job trainer-job

      # 16. Debug - Trainer pod logs
      - name: Debug - Trainer pod logs
        run: |
          POD=$(kubectl get pods --selector=job-name=trainer-job -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD || true

      # 17. Wait for trainer job completion
      - name: Wait for trainer job completion
        run: kubectl wait --for=condition=complete --timeout=600s job/trainer-job
