apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      imagePullSecrets:
        - name: ghcr-secret   # ensures it can pull from GHCR
      containers:
        - name: mlflow
          image: ghcr.io/YOUR_USERNAME/mlflow:latest   # update with your correct repo
          ports:
            - containerPort: 5000
          command: ["mlflow"]
          args:
            - server
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --backend-store-uri
            - sqlite:////mlflow/mlflow.db
            - --default-artifact-root
            - /mlflow
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: mlflow-data
          emptyDir: {}
