apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: cr.fly.dev/mlflow:latest # or build your own mlflow server image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_STORE_URI
              value: sqlite:///mlflow.db
            - name: ARTIFACT_ROOT
              value: /mlflow/mlruns
          volumeMounts:
            - mountPath: /mlflow
              name: mlflow-pv
      volumes:
        - name: mlflow-pv
          persistentVolumeClaim:
            claimName: mlflow-pvc
