name: MLflow CI/CD with kind

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mlflow-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up kind
        uses: engineerd/setup-kind@v0.6.0

      - name: Create kind cluster
        run: |
          kind create cluster --name mlflow-cluster

      - name: Build Docker image for MLflow
        run: |
          docker build -t mlflow-app:latest ./app
          kind load docker-image mlflow-app:latest --name mlflow-cluster

      - name: Apply MLflow Kubernetes resources
        run: |
          kubectl apply -f k8s/mlflow-deployment.yaml
          kubectl apply -f k8s/mlflow-service.yaml
          kubectl apply -f k8s/mlflow-job.yaml

      - name: Wait for MLflow Job to start
        run: |
          kubectl wait --for=condition=ready pod -l job-name=mlflow-job -n mlflow --timeout=180s

      - name: Get logs from MLflow Job
        run: |
          POD=$(kubectl get pods -n mlflow -l job-name=mlflow-job -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD -n mlflow -f

      - name: Verify all pods
        run: kubectl get pods -n mlflow
