name: CI/CD Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to GHCR using PAT
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 5. Set lowercase username
      - name: Set lowercase username
        id: lowername
        run: echo "username_lc=${GITHUB_ACTOR,,}" >> $GITHUB_OUTPUT

      # 6. Build and push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest

      # 7. Setup kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      # 8. Decode kubeconfig
      - name: Decode Kubeconfig
        env:
          KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_B64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      # 9. Optional: Test cluster connectivity
      - name: Test cluster connectivity
        run: |
          kubectl cluster-info
          kubectl get nodes || echo "Cluster not reachable from runner"

      # 10. Replace image placeholder in K8s manifests
      - name: Replace image in K8s manifests
        run: |
          sed -i "s|{{IMAGE_PLACEHOLDER}}|ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest|g" k8s/trainer-job.yaml

      # 11. Apply Kubernetes manifests
      - name: Apply K8s manifests
        run: |
          kubectl apply --validate=false -f k8s/mlflow-pv-pvc.yaml
          kubectl apply --validate=false -f k8s/mlflow-deployment.yaml
          kubectl apply --validate=false -f k8s/mlflow-service.yaml
          kubectl apply --validate=false -f k8s/trainer-job.yaml
