name: MLflow CI/CD (Local Cluster)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image locally
        run: |
          docker build -t mlflow-app:latest .

      - name: Load Docker image into Kubernetes
        run: |
          # If using kind or k3d, load image into cluster
          # For example, if using kind:
          kind load docker-image mlflow-app:latest --name mlflow-cluster

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Delete previous MLflow Job
        run: kubectl delete job mlflow-job -n mlflow --ignore-not-found

      - name: Apply MLflow Job YAML
        run: kubectl apply -f k8s/mlflow-job.yaml

      - name: Verify pods
        run: kubectl get pods -n mlflow

      - name: Check logs for one pod
        run: |
          POD=$(kubectl get pods -n mlflow -l job-name=mlflow-job -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD -n mlflow -f
