name: CI/CD Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: your-dockerhub-username
          password: your-dockerhub-password-or-token

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: docker.io/your-dockerhub-username/mlflow-trainer:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "
          apiVersion: v1
          clusters:
          - cluster:
              server: https://<your-k8s-api-server>
              certificate-authority-data: <base64-ca-cert>
            name: my-cluster
          contexts:
          - context:
              cluster: my-cluster
              user: my-user
            name: my-context
          current-context: my-context
          kind: Config
          preferences: {}
          users:
          - name: my-user
            user:
              token: <your-k8s-bearer-token>
          " > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Replace image in K8s manifests
        run: |
          sed -i "s|{{IMAGE_PLACEHOLDER}}|docker.io/your-dockerhub-username/mlflow-trainer:latest|g" k8s/trainer-job.yaml

      - name: Apply K8s manifests
        run: |
          kubectl apply -f k8s/mlflow-pv-pvc.yaml
          kubectl apply -f k8s/mlflow-deployment.yaml
          kubectl apply -f k8s/mlflow-service.yaml
          kubectl apply -f k8s/trainer-job.yaml
