name: CI/CD Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set lowercase username
        id: lowername
        run: echo "username_lc=${GITHUB_ACTOR,,}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Decode Kubeconfig
        env:
          KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG_B64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Test cluster connectivity
        run: |
          kubectl cluster-info
          kubectl get nodes || echo "Cluster not reachable from runner"

      - name: Replace image in K8s manifests
        run: |
          sed -i "s|{{IMAGE_PLACEHOLDER}}|ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest|g" k8s/trainer-job.yaml

      - name: Apply K8s manifests
        run: |
          kubectl apply --validate=false -f k8s/mlflow-pv-pvc.yaml
          kubectl apply --validate=false -f k8s/mlflow-deployment.yaml
          kubectl apply --validate=false -f k8s/mlflow-service.yaml
          kubectl apply --validate=false -f k8s/trainer-job.yaml
