name: CI/CD Build, Push, Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_USERNAME }}/mlflow-trainer:latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Decode Kubeconfig
        env:
          KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG_B64" | base64 --decode > kubeconfig
          mkdir -p ~/.kube
          mv kubeconfig ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Replace image in K8s manifests
        run: |
          # simple sed replace. Ensure your k8s/trainer-job.yaml uses {{IMAGE_PLACEHOLDER}}
          sed -i "s|{{IMAGE_PLACEHOLDER}}|${{ env.IMAGE_NAME }}|g" k8s/trainer-job.yaml

      - name: Apply K8s manifests
        run: |
          kubectl apply -f k8s/mlflow-pv-pvc.yaml
          kubectl apply -f k8s/mlflow-deployment.yaml
          kubectl apply -f k8s/mlflow-service.yaml
          kubectl apply -f k8s/trainer-job.yaml
