name: MLflow CI/CD (Docker Desktop)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image locally
        run: |
          docker build -t mlflow-app:latest ./app

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Delete previous MLflow Job
        run: kubectl delete job mlflow-job -n mlflow --ignore-not-found

      - name: Apply MLflow Job YAML
        run: kubectl apply -f k8s/mlflow-job.yaml

      - name: Verify pods
        run: kubectl get pods -n mlflow

      - name: Check logs for first pod
        run: |
          POD=$(kubectl get pods -n mlflow -l job-name=mlflow-job -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD -n mlflow -f
