name: CI/CD Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 5️⃣ Set lowercase username
      - name: Set lowercase username
        id: lowername
        run: echo "username_lc=${GITHUB_ACTOR,,}" >> $GITHUB_OUTPUT

      # 6️⃣ Build and push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest

      # 7️⃣ Set up Kind (Kubernetes in Docker)
      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.20.0

      # 8️⃣ Create Kind cluster
      - name: Create Kind cluster
        run: kind create cluster --name mlflow-ci --wait 60s

      # 9️⃣ Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      # 🔹 Ensure kubectl uses Kind context
      - name: Use Kind context
        run: kubectl cluster-info --context kind-mlflow-ci

      # 🔟 Replace image placeholder in trainer-job.yaml
      - name: Replace image in K8s manifests
        run: |
          sed -i "s|your-registry/mlflow-trainer:latest|ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest|g" k8s/trainer-job.yaml

      # 1️⃣1️⃣ Apply PersistentVolume & PVC first
      - name: Apply MLflow PV & PVC
        run: kubectl apply -f k8s/mlflow-pv-pvc.yaml

      # 1️⃣2️⃣ Apply MLflow Deployment
      - name: Apply MLflow Deployment
        run: kubectl apply -f k8s/mlflow-deployment.yaml

      # 1️⃣3️⃣ Apply MLflow Service
      - name: Apply MLflow Service
        run: kubectl apply -f k8s/mlflow-service.yaml

      # 1️⃣4️⃣ Apply Trainer Job
      - name: Apply Trainer Job
        run: kubectl apply -f k8s/trainer-job.yaml

      # 1️⃣5️⃣ Wait for trainer job to complete
      - name: Wait for trainer job completion
        run: kubectl wait --for=condition=complete --timeout=600s job/trainer-job
