name: CI/CD Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 5. Set lowercase username
      - name: Set lowercase username
        id: lowername
        run: echo "username_lc=${GITHUB_ACTOR,,}" >> $GITHUB_OUTPUT

      # 6. Build and push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest

      # 7. Set up Kind (Kubernetes in Docker)
      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.20.0

      # 8. Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      # 9. Replace image placeholder in K8s manifests
      - name: Replace image in K8s manifests
        run: |
          sed -i "s|{{IMAGE_PLACEHOLDER}}|ghcr.io/${{ steps.lowername.outputs.username_lc }}/mlflow-trainer:latest|g" k8s/trainer-job.yaml

      # 10. Apply Kubernetes manifests
      - name: Apply K8s manifests
        run: |
          kubectl apply -f k8s/mlflow-pv-pvc.yaml
          kubectl apply -f k8s/mlflow-deployment.yaml
          kubectl apply -f k8s/mlflow-service.yaml
          kubectl apply -f k8s/trainer-job.yaml
